<?php


namespace App\Services;


use App\Repositories\PostRepository;
use Illuminate\Support\Facades\Log;

class PostService extends AbstractService
{
    public function __construct(PostRepository $repository)
    {
        parent::__construct($repository);
    }

    public function view($model)
    {

        return parent::view($model); // TODO: Change the autogenerated stub
    }
}
